### ISSUE TITLE
name 'nn' is not defined

### ISSUE THREAD

**Issue by cyang49** [HankKung/LogPred#2]
Hank, here's another bug
```
(wmlce-1.7.0) c699c056:LogPred ccyang$ python train.py -model dl -num_layers 2 -hidden_size 128 -window_size 10 -dataset hd -epoch 300
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from deeplog.model import *
  File "/gpfs/wscgpfs01/ccyang/LogPred/deeplog/model.py", line 1, in <module>
    class DL(nn.Module):
NameError: name 'nn' is not defined
```

**Comment by HankKung** [comment]
I've updated the fixed one and rerun all training/eval files, it should all right now, thanks!!
